// Code generated by MockGen. DO NOT EDIT.
// Source: step.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSteper is a mock of Steper interface.
type MockSteper struct {
	ctrl     *gomock.Controller
	recorder *MockSteperMockRecorder
}

// MockSteperMockRecorder is the mock recorder for MockSteper.
type MockSteperMockRecorder struct {
	mock *MockSteper
}

// NewMockSteper creates a new mock instance.
func NewMockSteper(ctrl *gomock.Controller) *MockSteper {
	mock := &MockSteper{ctrl: ctrl}
	mock.recorder = &MockSteperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSteper) EXPECT() *MockSteperMockRecorder {
	return m.recorder
}

// Finish mocks base method.
func (m *MockSteper) Finish(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finish", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Finish indicates an expected call of Finish.
func (mr *MockSteperMockRecorder) Finish(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finish", reflect.TypeOf((*MockSteper)(nil).Finish), ctx)
}

// Run mocks base method.
func (m *MockSteper) Run(ctx context.Context) (context.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockSteperMockRecorder) Run(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockSteper)(nil).Run), ctx)
}

// String mocks base method.
func (m *MockSteper) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockSteperMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockSteper)(nil).String))
}
