# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - "go mod tidy"
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - "linux"
      - "darwin"
    goarch:
      - "amd64"
      - "386"
      - "arm"
      - "arm64"
    goarm:
      - "5"
      - "6"
      - "7"
    ldflags:
      - -s -w
      - "-X github.com/mrlyc/cmdr/define.Version={{.Version}}"
      - "-X github.com/mrlyc/cmdr/define.Commit={{.Commit}}"
      - "-X github.com/mrlyc/cmdr/define.BuildDate={{.Date}}"
      - "-X github.com/mrlyc/cmdr/define.Asset={{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
