# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - "go mod tidy"
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - "linux"
      - "darwin"
    goarch:
      - "amd64"
      - "386"
      - "arm"
      - "arm64"
    goarm:
      - "5"
      - "6"
      - "7"
    ldflags:
      - -s -w
      - "-X github.com/mrlyc/cmdr/core.Version={{.Version}}"
      - "-X github.com/mrlyc/cmdr/core.Commit={{.Commit}}"
      - "-X github.com/mrlyc/cmdr/core.BuildDate={{.Date}}"
      - "-X github.com/mrlyc/cmdr/core.Asset={{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
upx:
  - # Whether to enable it or not.
    enabled: true
    # Compress argument.
    # Valid options are from '1' (faster) to '9' (better), and 'best'.
    compress: "1"
    # Whether to try LZMA (slower).
    lzma: false
    # Whether to try all methods and filters (slow).
    brute: true
