// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CommandsColumns holds the columns for the "commands" table.
	CommandsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "activated", Type: field.TypeBool, Default: false},
		{Name: "name", Type: field.TypeString, Size: 128},
		{Name: "version", Type: field.TypeString, Size: 128},
		{Name: "location", Type: field.TypeString, Size: 512},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "managed", Type: field.TypeBool, Default: false},
	}
	// CommandsTable holds the schema information for the "commands" table.
	CommandsTable = &schema.Table{
		Name:       "commands",
		Columns:    CommandsColumns,
		PrimaryKey: []*schema.Column{CommandsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "command_name_version",
				Unique:  true,
				Columns: []*schema.Column{CommandsColumns[2], CommandsColumns[3]},
			},
			{
				Name:    "command_activated",
				Unique:  false,
				Columns: []*schema.Column{CommandsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CommandsTable,
	}
)

func init() {
}
