// Code generated by "stringer -type=CommandProvider"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CommandProviderUnknown-0]
	_ = x[CommandProviderDefault-1]
	_ = x[CommandProviderDatabase-2]
	_ = x[CommandProviderBinary-3]
	_ = x[CommandProviderDownload-4]
	_ = x[CommandProviderDoctor-5]
}

const _CommandProvider_name = "CommandProviderUnknownCommandProviderDefaultCommandProviderDatabaseCommandProviderBinaryCommandProviderDownloadCommandProviderDoctor"

var _CommandProvider_index = [...]uint8{0, 22, 44, 67, 88, 111, 132}

func (i CommandProvider) String() string {
	if i < 0 || i >= CommandProvider(len(_CommandProvider_index)-1) {
		return "CommandProvider(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandProvider_name[_CommandProvider_index[i]:_CommandProvider_index[i+1]]
}
