// Code generated by "stringer -type=ModelType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModelTypeUnknown-0]
	_ = x[ModelTypeCommand-1]
}

const _ModelType_name = "ModelTypeUnknownModelTypeCommand"

var _ModelType_index = [...]uint8{0, 16, 32}

func (i ModelType) String() string {
	if i < 0 || i >= ModelType(len(_ModelType_index)-1) {
		return "ModelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ModelType_name[_ModelType_index[i]:_ModelType_index[i+1]]
}
