// Code generated by "stringer -type=CommandProvider"; DO NOT EDIT.

package cmdr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CommandProviderUnknown-0]
	_ = x[CommandProviderDatabase-1]
	_ = x[CommandProviderBinary-2]
	_ = x[CommandProviderSimple-3]
}

const _CommandProvider_name = "CommandProviderUnknownCommandProviderDatabaseCommandProviderBinaryCommandProviderSimple"

var _CommandProvider_index = [...]uint8{0, 22, 45, 66, 87}

func (i CommandProvider) String() string {
	if i < 0 || i >= CommandProvider(len(_CommandProvider_index)-1) {
		return "CommandProvider(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandProvider_name[_CommandProvider_index[i]:_CommandProvider_index[i+1]]
}
