// Code generated by entc, DO NOT EDIT.

package command

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the command type in the database.
	Label = "command"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldActivated holds the string denoting the activated field in the database.
	FieldActivated = "activated"
	// Table holds the table name of the command in the database.
	Table = "commands"
)

// Columns holds all SQL columns for command fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldName,
	FieldVersion,
	FieldLocation,
	FieldActivated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// LocationValidator is a validator for the "location" field. It is called by the builders before save.
	LocationValidator func(string) error
	// DefaultActivated holds the default value on creation for the "activated" field.
	DefaultActivated bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
