// Code generated by "stringer -type=ContextKey"; DO NOT EDIT.

package define

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContextKeyDBClient-0]
	_ = x[ContextKeyConfiguration-1]
	_ = x[ContextKeyCommands-2]
}

const _ContextKey_name = "ContextKeyDBClientContextKeyConfigurationContextKeyCommands"

var _ContextKey_index = [...]uint8{0, 18, 41, 59}

func (i ContextKey) String() string {
	if i < 0 || i >= ContextKey(len(_ContextKey_index)-1) {
		return "ContextKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContextKey_name[_ContextKey_index[i]:_ContextKey_index[i+1]]
}
