// Code generated by "stringer -type=ContextKey"; DO NOT EDIT.

package define

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContextKeyName-0]
	_ = x[ContextKeyVersion-1]
	_ = x[ContextKeyLocation-2]
	_ = x[ContextKeyDBClient-3]
	_ = x[ContextKeyCommandManaged-4]
	_ = x[ContextKeyCommands-5]
	_ = x[ContextKeyCommand-6]
}

const _ContextKey_name = "ContextKeyNameContextKeyVersionContextKeyLocationContextKeyDBClientContextKeyCommandManagedContextKeyCommandsContextKeyCommand"

var _ContextKey_index = [...]uint8{0, 14, 31, 49, 67, 91, 109, 126}

func (i ContextKey) String() string {
	if i < 0 || i >= ContextKey(len(_ContextKey_index)-1) {
		return "ContextKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContextKey_name[_ContextKey_index[i]:_ContextKey_index[i+1]]
}
