// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package operator

import (
	"context"
	"github.com/google/wire"
	"github.com/mrlyc/cmdr/config"
)

// Injectors from wire.go:

func GetBinDir(ctx context.Context) string {
	viper := config.GetConfigurationFromContext(ctx)
	string2 := config.GetBinDir(viper)
	return string2
}

func GetShimsDir(ctx context.Context) string {
	viper := config.GetConfigurationFromContext(ctx)
	string2 := config.GetBinDir(viper)
	return string2
}

func GetDatabasePath(ctx context.Context) string {
	viper := config.GetConfigurationFromContext(ctx)
	string2 := config.GetDatabasePath(viper)
	return string2
}

// wire.go:

var (
	binDirSet   = wire.NewSet(config.GetConfigurationFromContext, config.GetBinDir)
	shimsDirSet = wire.NewSet(config.GetConfigurationFromContext, config.GetShimsDir)
	dbSet       = wire.NewSet(config.GetConfigurationFromContext, config.GetDatabasePath)
)
