on: [pull_request]
name: integration-test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: debug
        run: curl https://api.github.com/repos/MrLYC/cmdr/releases/latest